import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';
import { user } from '@/db/auth-schema';

/**
 * App-owned tables (not generated by Better Auth)
 * Add your custom application tables here
 */

/**
 * Team — created by a captain, up to 4 members.
 * inviteSlug is a URL-safe slug derived from the team name (e.g. "cool-hackers").
 */
export const team = sqliteTable('team', {
  id: text('id').primaryKey(), // crypto.randomUUID()
  name: text('name').notNull().unique(),
  // Canonicalized form of team name for case-insensitive uniqueness checks.
  nameCanonical: text('name_canonical').notNull().unique(),
  inviteSlug: text('invite_slug').notNull().unique(),
  captainId: text('captain_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
});

export type Team = typeof team.$inferSelect;
export type NewTeam = typeof team.$inferInsert;

/**
 * Participant — filled in during onboarding (step 2 of registration).
 * teamId is nullable; set when the participant joins or creates a team.
 */
export const participant = sqliteTable(
  'participant',
  {
    id: text('id')
      .primaryKey()
      .references(() => user.id, { onDelete: 'cascade' }),
    fullName: text('full_name').notNull(),
    iin: text('iin').notNull(),
    phone: text('phone').notNull(),
    city: text('city').notNull(),
    placeOfStudy: text('place_of_study').notNull(),
    parentPhone: text('parent_phone'),
    educationLevel: text('education_level').notNull(),
    cvUrl: text('cv_url'),
    teamId: text('team_id').references(() => team.id, { onDelete: 'set null' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
  },
  (table) => [index('idx_participant_team_id').on(table.teamId)],
);

export type Participant = typeof participant.$inferSelect;
export type NewParticipant = typeof participant.$inferInsert;

// ── Relations ────────────────────────────────────────────────────────────────

export const teamRelations = relations(team, ({ many, one }) => ({
  members: many(participant),
  captain: one(participant, { fields: [team.captainId], references: [participant.id] }),
}));

export const participantRelations = relations(participant, ({ one }) => ({
  team: one(team, { fields: [participant.teamId], references: [team.id] }),
  user: one(user, { fields: [participant.id], references: [user.id] }),
}));
