import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { user } from './auth-schema';

/**
 * App-owned tables (not generated by Better Auth)
 * Add your custom application tables here
 */

/**
 * Participant — filled in during onboarding (step 2 of registration)
 */
export const participant = sqliteTable('participant', {
  id: text('id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  fullName: text('full_name').notNull(),
  iin: text('iin').notNull(),
  phone: text('phone').notNull(),
  educationLevel: text('education_level').notNull(),
  cvUrl: text('cv_url'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
});

export type Participant = typeof participant.$inferSelect;
export type NewParticipant = typeof participant.$inferInsert;
